//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace Model
{
	/// <summary>
	/// Database       : mydb
	/// Data Source    : localhost
	/// Server Version : 5.5.5-10.4.11-MariaDB
	/// </summary>
	public partial class MydbDB : LinqToDB.Data.DataConnection
	{
		public ITable<Car>      Cars      { get { return this.GetTable<Car>(); } }
		public ITable<Carbrand> Carbrands { get { return this.GetTable<Carbrand>(); } }
		public ITable<Carmodel> Carmodels { get { return this.GetTable<Carmodel>(); } }

		public MydbDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public MydbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("car")]
	public partial class Car
	{
		[Column("car_id"),        PrimaryKey, Identity] public int      CarId        { get; set; } // int(11)
		[Column("car_builtdate"), NotNull             ] public DateTime CarBuiltdate { get; set; } // datetime
		[Column("cam_id"),        NotNull             ] public int      CamId        { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// fk_car_carmodel
		/// </summary>
		[Association(ThisKey="CamId", OtherKey="CamId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="fk_car_carmodel", BackReferenceName="Fkcars")]
		public Carmodel Cam { get; set; }

		#endregion
	}

	[Table("carbrand")]
	public partial class Carbrand
	{
		[Column("cab_id"),   PrimaryKey, Identity] public int    CabId   { get; set; } // int(11)
		[Column("cab_name"), NotNull             ] public string CabName { get; set; } // varchar(45)

		#region Associations

		/// <summary>
		/// fk_carmodel_carbrand1_BackReference
		/// </summary>
		[Association(ThisKey="CabId", OtherKey="CabId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Carmodel> Fkcarmodelcarbrands { get; set; }

		#endregion
	}

	[Table("carmodel")]
	public partial class Carmodel
	{
		[Column("cam_id"),    PrimaryKey, Identity] public int    CamId    { get; set; } // int(11)
		[Column("cam_model"), NotNull             ] public string CamModel { get; set; } // varchar(45)
		[Column("cam_ps"),    NotNull             ] public int    CamPs    { get; set; } // int(11)
		[Column("cab_id"),    NotNull             ] public int    CabId    { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// fk_carmodel_carbrand1
		/// </summary>
		[Association(ThisKey="CabId", OtherKey="CabId", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="fk_carmodel_carbrand1", BackReferenceName="Fkcarmodelcarbrands")]
		public Carbrand Cab { get; set; }

		/// <summary>
		/// fk_car_carmodel_BackReference
		/// </summary>
		[Association(ThisKey="CamId", OtherKey="CamId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Car> Fkcars { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Car Find(this ITable<Car> table, int CarId)
		{
			return table.FirstOrDefault(t =>
				t.CarId == CarId);
		}

		public static Carbrand Find(this ITable<Carbrand> table, int CabId)
		{
			return table.FirstOrDefault(t =>
				t.CabId == CabId);
		}

		public static Carmodel Find(this ITable<Carmodel> table, int CamId)
		{
			return table.FirstOrDefault(t =>
				t.CamId == CamId);
		}
	}
}

#pragma warning restore 1591
